### ISSUE TITLE
[parser] Parser segfaults without arguments on linux

### ISSUE THREAD

**Issue by tjammer** [raysan5/raylib#1824]
### Issue description

The new parser (`parser/raylib_parser.c`) segfaults on Linux when the executable is called without any arguments.
This is due to argv[1]=0x0, which is then passed to IsTextEqual unchecked

### Environment

I'm running openSUSE Tumbleweed on x86_64 and compiling with gcc 11

### Issue Screenshot
```
 $ gcc -g raylib_parser.c 
✔ /tmp/tmp.oEAxeoc0lK/raylib/parser [master|…2] 
 $ gdb ./a.out 
(gdb) r
Starting program: /tmp/tmp.oEAxeoc0lK/raylib/parser/a.out

Program received signal SIGSEGV, Segmentation fault.
0x00000000004038f8 in IsTextEqual (text1=0x0, text2=0x404008 "--help", count=6) at raylib_parser.c:738
738             if (text1[i] != text2[i]) 
(gdb) bt
#0  0x00000000004038f8 in IsTextEqual (text1=0x0, text2=0x404008 "--help", count=6) at raylib_parser.c:738
#1  0x0000000000401231 in main (argc=1, argv=0x7fffffffdb78) at raylib_parser.c:118

```

**Comment by tjammer** [comment]
Maybe a stage could be added to the CI to protect against regressions like this in the future
