### ISSUE TITLE
[examples] Valgrind finds memory leaks on the simple website examples.

### ISSUE THREAD

**Issue by bigooff** [raysan5/raylib#3348]
### Issue description

I am using the raylib.com examples to check if my compilation and linking is correct.

(i only tested the first 2 examples)
Everything works as expected and the example is completely functional but 
when i compile with address sanitizer or i check the binary after with valgrind,
i get memory leak errors.

I looked around in the issues and didn't find something like this so it might not be raylibs fault.
No matter what i do i cant get rid of this and this happens after i close the window with X.

I have tried using different compilers , combinations of cflags and linker flags
I have compiled raylib as a static library.
### Environment

ubuntu 22.0.4
raylib-4.6
VSCode
gnu make 4.3
gcc 11.4.0
integrated graphics

OpenGL info:
```INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 213
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
```

### Valgrind output
$ valgrind --leak-check=full ./build/debug/main.elf
```
==11843== Memcheck, a memory error detector
==11843== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11843== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==11843== Command: ./build/debug/main.elf
==11843== 
INFO: Initializing raylib 4.6-dev
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1360 x 768
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 213
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
==11843== 
==11843== HEAP SUMMARY:
==11843==     in use at exit: 249,074 bytes in 3,346 blocks
==11843==   total heap usage: 73,152 allocs, 69,806 frees, 14,053,460 bytes allocated
==11843== 
==11843== 0 bytes in 2 blocks are definitely lost in loss record 1 of 2,230
==11843==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==11843==    by 0x4005A22: malloc (rtld-malloc.h:56)
==11843==    by 0x4005A22: _dl_find_object_update (dl-find_object.c:791)
==11843==    by 0x400ECCF: dl_open_worker_begin (dl-open.c:735)
==11843==    by 0x50FFC47: _dl_catch_exception (dl-error-skeleton.c:208)
==11843==    by 0x400DF99: dl_open_worker (dl-open.c:782)
==11843==    by 0x50FFC47: _dl_catch_exception (dl-error-skeleton.c:208)
==11843==    by 0x400E34D: _dl_open (dl-open.c:883)
==11843==    by 0x501B6BB: dlopen_doit (dlopen.c:56)
==11843==    by 0x50FFC47: _dl_catch_exception (dl-error-skeleton.c:208)
==11843==    by 0x50FFD12: _dl_catch_error (dl-error-skeleton.c:227)
==11843==    by 0x501B1AD: _dlerror_run (dlerror.c:138)
==11843==    by 0x501B747: dlopen_implementation (dlopen.c:71)
==11843==    by 0x501B747: dlopen@@GLIBC_2.34 (dlopen.c:81)
==11843== 
==11843== 408 bytes in 1 blocks are definitely lost in loss record 2,203 of 2,230
==11843==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==11843==    by 0x5DDB93F: _XimOpenIM (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==11843==    by 0x5DE14EC: _XimRegisterIMInstantiateCallback (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==11843==    by 0x5DCDB1C: XRegisterIMInstantiateCallback (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==11843==    by 0x174514: _glfwInitX11 (in /home/user/Projects/first_raylib_proj/build/debug/main.elf)
==11843==    by 0x16FE46: glfwInit (in /home/user/Projects/first_raylib_proj/build/debug/main.elf)
==11843==    by 0x13172D: InitWindow (in /home/user/Projects/first_raylib_proj/build/debug/main.elf)
==11843==    by 0x11008C: main (main.c:13)
==11843== 
==11843== LEAK SUMMARY:
==11843==    definitely lost: 408 bytes in 3 blocks
==11843==    indirectly lost: 0 bytes in 0 blocks
==11843==      possibly lost: 0 bytes in 0 blocks
==11843==    still reachable: 248,666 bytes in 3,343 blocks
==11843==         suppressed: 0 bytes in 0 blocks
==11843== Reachable blocks (those to which a pointer was found) are not shown.
==11843== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==11843== 
==11843== For lists of detected and suppressed errors, rerun with: -s
==11843== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
```
### ASAN output

Raylib's output code is the same as above.

```
=================================================================
==12292==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 408 byte(s) in 1 object(s) allocated from:
    #0 0x7fe492cb4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fe491f2193f in _XimOpenIM (/lib/x86_64-linux-gnu/libX11.so.6+0x6193f)

SUMMARY: AddressSanitizer: 408 byte(s) leaked in 1 allocation(s).
```
### Code Example
```
#include "raylib.h"

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - keyboard input");

    Vector2 ballPosition = { (float)screenWidth/2, (float)screenHeight/2 };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        if (IsKeyDown(KEY_RIGHT)) ballPosition.x += 2.0f;
        if (IsKeyDown(KEY_LEFT)) ballPosition.x -= 2.0f;
        if (IsKeyDown(KEY_UP)) ballPosition.y -= 2.0f;
        if (IsKeyDown(KEY_DOWN)) ballPosition.y += 2.0f;
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("move the ball with arrow keys", 10, 10, 20, DARKGRAY);

            DrawCircleV(ballPosition, 50, MAROON);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by raysan5** [comment]
@bigooff I'm afraid those leaks are out-of-scope of raylib but related to system libraries.

**Comment by bigooff** [comment]
okay thanks a lot i'll look into it.
