### ISSUE TITLE
[build] OSX Segmentation Fault on light_my_ritual game example

### ISSUE THREAD

**Issue by SethArchambault** [raysan5/raylib#353]
When running raylib/games/light_my_ritual on a mid-2010 mac (v 10.12.6) I'm getting a segmentation fault in 

Here's the backtrace from GDB
```
#0  0x000000010003c359 in stb_vorbis_seek_start ()
#1  0x000000010000871f in StopMusicStream ()
#2  0x0000000100000c1c in UpdateDrawFrame ()
#3  0x0000000100000a65 in main ()
```

Here's the messages in the console:

```
[New Thread 0x1403 of process 38484]
warning: unhandled dyld version (15)
INFO: Initializing raylib (v1.8.0)
INFO: Display device initialized successfully
INFO: Display size: 1280 x 800
INFO: Render size: 1280 x 720
INFO: Screen size: 1280 x 720
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   NVIDIA Corporation
INFO: GPU: Renderer: NVIDIA GeForce 320M OpenGL Engine
INFO: GPU: Version:  3.3 NVIDIA-10.2.37 310.90.10.05b54
INFO: GPU: GLSL:     3.30
INFO: Number of supported extensions: 37
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [EXTENSION] Clamp mirror wrap texture mode supported
INFO: [TEX ID 1] Texture created successfully (1x1)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [VSHDR ID 1] Vertex shader compiled successfully
INFO: [FSHDR ID 2] Fragment shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Audio device and context initialized successfully: Built-in Output
WARNING: [resources/lights_map.png] Image could not be loaded
WARNING: [resources/font_arcadian.png] Image could not be loaded
WARNING: [resources/font_arcadian.png] SpriteFont could not be loaded, using default font
WARNING: [resources/audio/ambient.ogg] OGG audio file could not be opened
INFO: Target time per frame: 16.667 milliseconds
WARNING: [resources/textures/back_title.png] Image could not be loaded
WARNING: Texture could not be created
WARNING: [resources/textures/title.png] Image could not be loaded
WARNING: Texture could not be created
WARNING: [resources/audio/start.wav] WAV file could not be opened
INFO: Unloaded wave data from RAM
[New Thread 0x1207 of process 38484]
[New Thread 0x1503 of process 38484]
[New Thread 0x1603 of process 38484]
[New Thread 0x1703 of process 38484]
```

So it looks like the music file is not loading properly, and then when it is stopped, this causes a segmentation fault. 
Of course, all of those files are in the right place.. I wonder if this is related to Mac OSX security precautions related to file placement..

**Comment by raysan5** [comment]
Looking at the output, it seems there is some problem with resources path, it seems the resources could not be found... that's related to OSX app default paths...

**Comment by raysan5** [comment]
Closing this issue because it's posibly a dup of https://github.com/raysan5/raylib/issues/339
